;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Tue Oct 28 2025
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

DATA SEGMENT
PORTA EQU 0F0H
PORTB EQU 0F2H
PORTC EQU 0F4H
LEDARRAY DB 10000000B
SEVENDSP DB 0
DIGITS DB 01111110B,00110000B,01101101B,01111001B,00110011B,01011011B,01011111B,01110000B,01111111B,01111011B
DATA ENDS

CODE SEGMENT PUBLIC 'CODE'
ASSUME CS:CODE, DS:DATA
ORG 0000H
START:
    MOV AX, DATA
    MOV DS, AX
    LEA SI, DIGITS

MAIN_LOOP:
    CALL DELAY
    MOV DX, PORTC
    IN AL, DX
    CMP AL, 01H
    JE LED_PROC
    CMP AL, 02H
    JE SSG_PROC
    JMP MAIN_LOOP

LED_PROC:
    ROR LEDARRAY, 1
    MOV AL, LEDARRAY
    MOV DX, PORTA
    OUT DX, AL
    JMP MAIN_LOOP

SSG_PROC:
    MOV BL, SEVENDSP
    MOV AL, [SI + BX]
    MOV DX, PORTB
    OUT DX, AL
    INC SEVENDSP
    CMP SEVENDSP, 0AH
    JB MAIN_LOOP
    SUB SEVENDSP, 0AH
    JMP MAIN_LOOP

DELAY:
    MOV CX, 0FFFFH
D1:
    PUSH CX
    MOV CX, 03E8H
D2:
    DEC CX
    JNZ D2
    POP CX
    DEC CX
    JNZ D1
    RET

CODE ENDS
END START