;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon Dec 1 2025
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

;====================================================================
; INTERRUPT SERVICE ROUTINE SEGMENT
;====================================================================
PROCED1 SEGMENT
   ISR0 PROC FAR
      ASSUME CS:PROCED1, DS:DATA
      ORG 01000H                    ; Interrupt service routine at fixed location
      
      ;=============================================================
      ; INTERRUPT PROLOGUE - Save registers
      ;=============================================================
      PUSHF                         ; Save flags
      PUSH AX                       ; Save AX register
      PUSH DX                       ; Save DX register
      
      ;=============================================================
      ; KEYPAD INTERRUPT HANDLER - Read keypad input
      ;=============================================================
   CHECK_DAVBL:
      MOV DX, PORTC                 ; DX = Keypad port address
      IN AL, DX                     ; Read keypad value
      
      AND AL, 0FH                   ; Mask higher nibble, keep lower 4 bits
      
      ;=============================================================
      ; KEYPAD INPUT DISPATCHING
      ; D(13) = Power ON/OFF, 0 = Temp Decrement, 1 = Temp Increment
      ; 2 = Fan Speed, C(12) = Swing Mode, E(14) = Mode Toggle
      ;=============================================================
      CMP AL, 0DH                   ; Check for 'D' key (Power ON/OFF)
      JE NUM_D                      
      CMP AL, 00H                   ; Check for '0' key (Decrement Temp)
      JE NUM1                       
      CMP AL, 01H                   ; Check for '1' key (Increment Temp)
      JE NUM2                       
      CMP AL, 02H                   ; Check for '2' key (Decrement Speed)
      JE NUM3                       
      CMP AL, 0CH                   ; Check for 'C' key (Swing Mode)
      JE NUMC                       
      CMP AL, 0EH                   ; Check for 'E' key (Mode Toggle)
      JE NUME                       
      
      JMP CHECK_DAVBL               ; If no valid key, keep checking
   
      ;=============================================================
      ; POWER BUTTON HANDLER (Key 'D')
      ;=============================================================
   NUM_D:
      MOV AL, POWER_FLAG            ; Load current power state
      
      CMP AL, 0                     ; Check if currently OFF
      JE SET1POWER                  ; If OFF, turn ON
      JNE SET0POWER                 ; If ON, turn OFF
      
   SET1POWER:                       ; Set POWER_FLAG to 1 (ON)
      MOV AL, 1
      JMP EXIT_NUM_D
      
   SET0POWER:                       ; Set POWER_FLAG to 0 (OFF)
      MOV AL, 0
      
   EXIT_NUM_D:
      MOV POWER_FLAG, AL            ; Save new power state
      JMP EXIT                      ; Exit interrupt

      ;=============================================================
      ; TEMPERATURE DECREMENT HANDLER (Key '0')
      ; Limits: 16°C minimum
      ;=============================================================
   NUM1:
      MOV AL, DTEMP                 ; Load current desired temperature
      CMP AL, 16                    ; Check minimum limit (16°C)
      JE EXIT_NUM1                  ; If at minimum, exit
      
      DEC AL                        ; Decrease temperature
      MOV DTEMP, AL                 ; Save new temperature
      
   EXIT_NUM1:
      JMP EXIT                      ; Exit interrupt

      ;=============================================================
      ; TEMPERATURE INCREMENT HANDLER (Key '1')
      ; Limits: 30°C maximum
      ;=============================================================
   NUM2:
      MOV AL, DTEMP                 ; Load current desired temperature
      CMP AL, 30                    ; Check maximum limit (30°C)
      JE EXIT_NUM2                  ; If at maximum, exit
      
      INC AL                        ; Increase temperature
      MOV DTEMP, AL                 ; Save new temperature
      
   EXIT_NUM2:
      JMP EXIT                      ; Exit interrupt

      ;=============================================================
      ; FAN SPEED CYCLE HANDLER (Key '2')
      ; Cycles through: LOW(0) ? MED(1) ? HIGH(2) ? LOW(0)
      ;=============================================================
   NUM3:
      MOV AL, FSPEED                ; Load current fan speed
      
      CMP AL, 0                     ; Check if current is LOW
      JE SET_MED_SPEED              ; LOW ? MED
      CMP AL, 1                     ; Check if current is MED
      JE SET_HIGH_SPEED             ; MED ? HIGH
      
      ; Current is HIGH, cycle back to LOW
      MOV AL, 0                     
      JMP EXIT_NUM3
      
   SET_MED_SPEED:                   ; Set to MEDIUM speed
      MOV AL, 1                     
      JMP EXIT_NUM3
      
   SET_HIGH_SPEED:                  ; Set to HIGH speed
      MOV AL, 2                     
      
   EXIT_NUM3:
      MOV FSPEED, AL                ; Save new fan speed
      JMP EXIT                      ; Exit interrupt

      ;=============================================================
      ; SWING MODE TOGGLE HANDLER (Key 'C')
      ;=============================================================
   NUMC:
      MOV AL, SWING_BUTTON          ; Load current swing state
      
      CMP AL, 0                     ; Check if currently OFF
      JE SET1SWING                  ; OFF ? ON
      JNE SET0SWING                 ; ON ? OFF
      
   SET1SWING:                       ; Set SWING_BUTTON to 1 (ON)
      MOV AL, 1
      JMP EXIT_NUMC
      
   SET0SWING:                       ; Set SWING_BUTTON to 0 (OFF)
      MOV AL, 0
      
   EXIT_NUMC:
      MOV SWING_BUTTON, AL          ; Save new swing state
      JMP EXIT                      ; Exit interrupt

      ;=============================================================
      ; MODE TOGGLE HANDLER (Key 'E')
      ; 0 = COOL Mode, 1 = FAN Only Mode
      ;=============================================================
   NUME:
      MOV AL, MODE_BUTTON           ; Load current mode
      
      CMP AL, 0                     ; Check if currently COOL mode
      JE SET1MODE                   ; COOL ? FAN
      JNE SET0MODE                  ; FAN ? COOL
      
   SET1MODE:                        ; Set MODE_BUTTON to 1 (FAN mode)
      MOV AL, 1
      JMP EXIT_NUME
      
   SET0MODE:                        ; Set MODE_BUTTON to 0 (COOL mode)
      MOV AL, 0
      
   EXIT_NUME:
      MOV MODE_BUTTON, AL           ; Save new mode
      
      ;=============================================================
      ; INTERRUPT EPILOGUE - Restore registers and return
      ;=============================================================
   EXIT:
      POP DX                        ; Restore DX register
      POP AX                        ; Restore AX register
      POPF                          ; Restore flags
      IRET                          ; Return from interrupt
      
   ISR0 ENDP
PROCED1 ENDS

;====================================================================
; DATA SEGMENT - Variables, Port Definitions, and String Messages
;====================================================================
DATA SEGMENT
   ORG 03000H                       ; Data segment starts at 3000H
   
   ;-----------------------------------------------------------------
   ; I/O PORT ADDRESSES
   ;-----------------------------------------------------------------
   PORTA    EQU 0C0H                ; LCD Data Port
   PORTB    EQU 0C2H                ; LCD Control Port
   PORTC    EQU 0C4H                ; Keypad Input Port
   COM_REG  EQU 0C6H                ; 8255 Command Register (Ports A,B,C)
   
   PORTD    EQU 0D0H                ; LED Control Port (Power/Compressor)
   PORTE    EQU 0D2H                ; Swing LED Control Port
   PORTF    EQU 0D4H                ; ADC0808 Input Port
   COM_REG2 EQU 0D6H                ; Secondary 8255 Command Register
   
   PORTG    EQU 0D8H                ; Fan Motor Enable Port
   PORTH    EQU 0DAH                ; Fan Speed Control Port
   PORTI    EQU 0DCH                ; Unused Port
   COM_REG3 EQU 0DEH                ; Tertiary 8255 Command Register
   
   ;-----------------------------------------------------------------
   ; 8259 PIC INITIALIZATION VALUES
   ;-----------------------------------------------------------------
   PIC1       EQU 0C8H              ; 8259 PIC Port 1
   PIC2       EQU 0CAH              ; 8259 PIC Port 2
   ICW1       EQU 13H               ; Initialization Command Word 1
   ICW2       EQU 84H               ; Initialization Command Word 2
   ICW4       EQU 03H               ; Initialization Command Word 4
   OCW1_ISR0  EQU 0FEH              ; Operation Command Word (Enable IR0)
   
   ;-----------------------------------------------------------------
   ; SYSTEM STATE VARIABLES
   ;-----------------------------------------------------------------
   POWER_FLAG    DB 0               ; 0 = OFF, 1 = ON
   DTEMP         DB 20              ; Desired Temperature (16-30°C)
   FSPEED        DB 0               ; Fan Speed: 0=LOW, 1=MED, 2=HIGH
   
   MODE_BUTTON   DB 0               ; 0 = COOL Mode, 1 = FAN Only Mode
   SWING_BUTTON  DB 0               ; 0 = Swing OFF, 1 = Swing ON
   ROOM_T        DB 0               ; Current Room Temperature (from ADC)
   TEMP          DB 0               ; Temporary variable
   
   ADC_ERROR_FLAG DB 0              ; 0 = No error, 1 = ADC error
   
   ;-----------------------------------------------------------------
   ; LCD DISPLAY MESSAGES
   ;-----------------------------------------------------------------
   COOL_MODE     DB "COOL MODE", "$"
   FAN_MODE      DB "FAN  MODE", "$"
   SWING_ON      DB "SWING  ON", "$"
   SWING_OFF     DB "SWING OFF", "$"
   
   LOW_MSG       DB "LOW ", "$"
   MED_MSG       DB "MED ", "$"
   HIGH_MSG      DB "HIGH", "$"
   
   RTEMP_MSG     DB "ROOM TEMP:", "$"
   DTEMP_MSG     DB "SET TEMP:", "$"
   FSPEED_MSG    DB "FAN SPEED:", "$"
   CELSIUS_MSG   DB ".0", "$"
   ERROR_MSG     DB "ERR", "$"      ; Error message for invalid ADC
   
   ;-----------------------------------------------------------------
   ; LOOKUP TABLES FOR ADC TEMPERATURE CONVERSION
   ; Maps ADC values (15H-4DH) to temperatures (12-45°C)
   ;-----------------------------------------------------------------
   ADC_VALUES    DB 15H, 16H, 18H, 1AH, 1BH, 1DH, 1FH, 21H, 22H
                 DB 24H, 26H, 27H, 29H, 2BH, 2CH, 2EH, 30H, 32H
                 DB 33H, 35H, 37H, 38H, 3AH, 3CH, 3EH, 3FH, 41H
                 DB 43H, 44H, 46H, 48H, 49H, 4BH, 4DH
   
   TEMP_VALUES   DB 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23
                 DB 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35
                 DB 36, 37, 38, 39, 40, 41, 42, 43, 44, 45
   
   TABLE_SIZE    EQU 34             ; Number of entries in lookup tables
   
DATA ENDS

;====================================================================
; STACK SEGMENT
;====================================================================
STK SEGMENT STACK
   BOS  DW 64 DUP(?)                ; Bottom of stack (64 words)
   TOS  LABEL WORD                  ; Top of stack label
STK ENDS

;====================================================================
; CODE SEGMENT - Main Program and Subroutines
;====================================================================
CODE SEGMENT PUBLIC 'CODE'
   ASSUME CS:CODE, DS:DATA, SS:STK
   ORG 08000H                       ; Code segment starts at 8000H
   
   ;=================================================================
   ; MAIN PROGRAM ENTRY POINT
   ;=================================================================
START:
   ;-----------------------------------------------------------------
   ; INITIALIZE SEGMENT REGISTERS AND STACK
   ;-----------------------------------------------------------------
   MOV AX, DATA                     ; Load data segment address
   MOV DS, AX                       ; Set DS to data segment
   MOV AX, STK                      ; Load stack segment address
   MOV SS, AX                       ; Set SS to stack segment
   LEA SP, TOS                      ; Set stack pointer to top of stack
   
   CLI                              ; Disable interrupts during setup
   
   ;-----------------------------------------------------------------
   ; INITIALIZE 8255 PROGRAMMABLE PERIPHERAL INTERFACE (PPI) CHIPS
   ;-----------------------------------------------------------------
   MOV DX, COM_REG                  ; Initialize primary 8255
   MOV AL, 89H                      ; Mode 0, Port A out, Port B out, Port C in
   OUT DX, AL
   
   MOV DX, COM_REG2                 ; Initialize secondary 8255
   MOV AL, 89H                      ; Same configuration
   OUT DX, AL
   
   MOV DX, COM_REG3                 ; Initialize tertiary 8255
   MOV AL, 89H                      ; Same configuration
   OUT DX, AL
   
   ;-----------------------------------------------------------------
   ; INITIALIZE 8259 PROGRAMMABLE INTERRUPT CONTROLLER (PIC)
   ;-----------------------------------------------------------------
   MOV DX, PIC1
   MOV AL, ICW1                     ; ICW1: Edge triggered, single 8259
   OUT DX, AL
   
   ;-----------------------------------------------------------------
   ; SETUP INTERRUPT VECTOR TABLE ENTRY FOR ISR0
   ; Vector for IR0 at interrupt 0x20 (vector 200H-203H)
   ;-----------------------------------------------------------------
   MOV AX, OFFSET ISR0              ; Offset of interrupt handler
   MOV [ES:200H], AX                ; Store in vector table
   MOV AX, SEG ISR0                 ; Segment of interrupt handler
   MOV [ES:202H], AX                ; Store in vector table
   
   ;-----------------------------------------------------------------
   ; INITIALIZE LCD DISPLAY
   ;-----------------------------------------------------------------
   CALL INIT_LCD
   
   ; Initialize ADC error flag
   MOV ADC_ERROR_FLAG, 0
   
   ;=================================================================
   ; MAIN FOREGROUND LOOP
   ;=================================================================
HERE:
   ;-----------------------------------------------------------------
   ; CHECK AC POWER STATUS
   ;-----------------------------------------------------------------
CHECK_AC:
   CALL EN_ISR0                     ; Enable ISR0 for keypad interrupts
   CALL INIT_LCD                    ; Initialize LCD display
   
   CMP POWER_FLAG, 0                ; Check if AC is powered ON
   JNZ TEMP_R                       ; If ON, jump to temperature display
   
   ; AC is OFF - Turn off all outputs
   MOV DX, PORTD                    ; Turn off LED indicators
   MOV AL, 00H
   OUT DX, AL
   
   MOV DX, PORTG                    ; Turn off fan motor
   MOV AL, 00H
   OUT DX, AL
   
   CALL OFF_SWING                   ; Turn off swing motor
   
   ; Reset all states to defaults
   MOV MODE_BUTTON, 0
   MOV SWING_BUTTON, 0
   MOV FSPEED, 0
   MOV DTEMP, 20
   MOV ADC_ERROR_FLAG, 0            ; Reset error flag when power is off
   
   JMP CHECK_AC                     ; Loop until powered ON
   
   ;-----------------------------------------------------------------
   ; DISPLAY TEMPERATURE AND SYSTEM STATUS ON LCD
   ; Line 1: "ROOM TEMP:XX°C"
   ; Line 2: "SET TEMP:XX°C"
   ; Line 3: "FAN SPEED:XXXX"
   ; Line 4: "|XXXX MODE SWING XXXX"
   ;-----------------------------------------------------------------
TEMP_R:                             ; Display room temperature header
   MOV DX, PORTD                    
   MOV AL, 0C0H                     ; Set cursor to first line, position 0
   CALL INST_CTRL
   LEA SI, RTEMP_MSG                ; Load "ROOM TEMP:" message
   CALL PRINT_STR
   
TEMP_D:                             ; Display desired temperature header
   MOV AL, 80H                      ; Set cursor to second line, position 0
   CALL INST_CTRL
   LEA SI, DTEMP_MSG                ; Load "SET TEMP:" message
   CALL PRINT_STR
   
SPEED_F:                            ; Display fan speed header
   MOV AL, 94H                      ; Set cursor to third line, position 0
   CALL INST_CTRL
   LEA SI, FSPEED_MSG               ; Load "FAN SPEED:" message
   CALL PRINT_STR
   
   ;=================================================================
   ; READ AND PROCESS ADC DATA (ROOM TEMPERATURE)
   ;=================================================================
GET_DATA:
   CALL EN_ISR0                     ; Enable keypad interrupts
   CMP POWER_FLAG, 0                ; Check if AC is still ON
   JZ CHECK_AC                      ; If OFF, return to power check
   
   ;-----------------------------------------------------------------
   ; READ ADC VALUE AND CONVERT TO TEMPERATURE USING LOOKUP TABLE
   ;-----------------------------------------------------------------
READ_ADC:
   MOV DX, PORTG                    ; Enable fan motor (low speed default)
   MOV AL, 01H
   OUT DX, AL
   
   MOV DX, PORTF                    ; Read ADC value from temperature sensor
   IN AL, DX
   
   ; Use lookup table to convert ADC value to temperature
   CALL LOOKUP_TEMP                 ; Returns temperature in AL (or 0 if not found)
   
   CMP AL, 0                        ; Check if valid temperature found
   JE ADC_ERROR                     ; If NOT found, display error
   
   ; Valid temperature found
   MOV ADC_ERROR_FLAG, 0            ; Clear error flag
   MOV ROOM_T, AL                   ; Store room temperature
   CALL DISPLAY_ROOMT               ; Display on LCD
   JMP DISP                         ; Go to display
   
ADC_ERROR:
   ; ADC value not in lookup table - display error
   MOV ADC_ERROR_FLAG, 1            ; Set error flag
   CALL DISPLAY_ROOMT               ; Display error on LCD
   
   ;=================================================================
   ; UPDATE SYSTEM DISPLAY AND CONTROL OUTPUTS
   ;=================================================================
DISP:
   XOR AX, AX                       ; Clear registers for calculations
   XOR CX, CX
   XOR DX, DX
   
   CALL DISP_DTEMP                  ; Display desired temperature
   CALL DISP_FSPEED                 ; Display fan speed
   
   ;-----------------------------------------------------------------
   ; DISPLAY SWING MODE STATUS
   ;-----------------------------------------------------------------
DISPSWING:
   MOV AL, 0DEH                     ; Set cursor to fourth line, position 2
   CALL INST_CTRL
   MOV AL, '|'                      ; Display separator
   CALL DATA_CTRL
   
   MOV AL, SWING_BUTTON             ; Check swing mode
   CMP AL, 0
   JE SWINGOFF                      ; Jump if swing is OFF
   JNE SWINGON                      ; Jump if swing is ON
   
SWINGOFF:                           ; Display "SWING OFF"
   MOV AL, 0DFH                     ; Set cursor position
   CALL INST_CTRL
   LEA SI, SWING_OFF
   CALL PRINT_STR
   CALL OFF_SWING                   ; Turn off swing motor
   JMP MODE
   
SWINGON:                            ; Display "SWING ON"
   MOV AL, 0DFH                     ; Set cursor position
   CALL INST_CTRL
   LEA SI, SWING_ON
   CALL PRINT_STR
   CALL ON_SWING                    ; Turn on swing motor
   JMP MODE
   
   ;-----------------------------------------------------------------
   ; DISPLAY OPERATING MODE
   ;-----------------------------------------------------------------
MODE:
   MOV AL, MODE_BUTTON              ; Check operating mode
   CMP AL, 0
   JE DISPCOOL                      ; Jump if COOL mode
   JNE DISPFAN                      ; Jump if FAN mode
   
DISPCOOL:                           ; Display "COOL MODE"
   MOV AL, 0D4H                     ; Set cursor position
   CALL INST_CTRL
   LEA SI, COOL_MODE
   CALL PRINT_STR
   
   ; Check if we should skip temperature control due to ADC error
   CMP ADC_ERROR_FLAG, 1
   JE GET_DATA                      ; Skip temperature control if ADC error
   
   JMP CHECK_TEMPERATURE            ; Check if compressor should run
   
DISPFAN:                            ; Display "FAN MODE"
   MOV AL, 0D4H                     ; Set cursor position
   CALL INST_CTRL
   LEA SI, FAN_MODE
   CALL PRINT_STR
   JMP OFF_COMPRESSOR               ; Turn off compressor in FAN mode
   
   ;-----------------------------------------------------------------
   ; TEMPERATURE CONTROL LOGIC (COOL MODE ONLY)
   ; Compressor runs when: Room Temp > Desired Temp + 3°C
   ; Compressor stops when: Room Temp <= Desired Temp
   ;-----------------------------------------------------------------
CHECK_TEMPERATURE:
   ; Skip temperature control if ADC has error
   CMP ADC_ERROR_FLAG, 1
   JE GET_DATA                      ; Skip to next reading if error
   
   MOV AL, DTEMP                    ; Load desired temperature
   MOV AH, ROOM_T                   ; Load room temperature
   
   CMP AH, AL                       ; Compare room temp with desired temp
   JLE OFF_COMPRESSOR               ; If room temp <= desired, turn off compressor
   
   ; Room temp > desired temp, check hysteresis
   MOV DH, DTEMP
   ADD DH, 3                       ; DH = desired temp + 3°C (hysteresis)
   CMP AH, DH                       ; Compare room temp with (desired + 3)
   JGE ON_COMPRESSOR                ; If room temp >= (desired + 1), turn on compressor
   
   JMP GET_DATA                     ; No change needed, continue monitoring
   
   ;-----------------------------------------------------------------
   ; END OF MAIN LOOP - RETURN TO MONITORING
   ;-----------------------------------------------------------------
ENDLESS:
   NOP                              ; Idle instruction
   JMP ENDLESS                      ; Infinite loop (should not reach here)
   
   ;=================================================================
   ; OUTPUT CONTROL SUBROUTINES
   ;=================================================================
ON_COMPRESSOR:                      ; Turn ON compressor LED
   MOV DX, PORTD
   MOV AL, 0011B                    ; Bits: Power LED + Compressor LED
   OUT DX, AL
   JMP GET_DATA
   
OFF_COMPRESSOR:                     ; Turn OFF compressor LED
   MOV DX, PORTD
   MOV AL, 0001B                    ; Bits: Power LED only
   OUT DX, AL
   JMP GET_DATA
   
ON_SWING:                           ; Turn ON swing motor
   MOV DX, PORTE
   MOV AL, 01H
   OUT DX, AL
   RET
   
OFF_SWING:                          ; Turn OFF swing motor
   MOV DX, PORTE
   MOV AL, 00H
   OUT DX, AL
   RET
   
   ;=================================================================
   ; LCD CONTROL SUBROUTINES
   ;=================================================================
INST_CTRL:                          ; Send instruction to LCD
   PUSH AX                          ; Save AX
   MOV DX, PORTA                    ; Send instruction byte
   OUT DX, AL
   MOV DX, PORTB                    ; Generate EN pulse
   MOV AL, 02H                      ; RS=0, RW=0, EN=1
   OUT DX, AL
   CALL DELAY_1MS                   ; Wait for LCD
   MOV DX, PORTB                    ; Clear EN pulse
   MOV AL, 00H                      ; RS=0, RW=0, EN=0
   OUT DX, AL
   POP AX                           ; Restore AX
   RET
   
DATA_CTRL:                          ; Send data to LCD
   PUSH AX                          ; Save AX
   MOV DX, PORTA                    ; Send data byte
   OUT DX, AL
   MOV DX, PORTB                    ; Generate EN pulse
   MOV AL, 03H                      ; RS=1, RW=0, EN=1
   OUT DX, AL
   CALL DELAY_1MS                   ; Wait for LCD
   MOV DX, PORTB                    ; Clear EN pulse
   MOV AL, 01H                      ; RS=1, RW=0, EN=0
   OUT DX, AL
   POP AX                           ; Restore AX
   RET
   
INIT_LCD:                           ; Initialize LCD display
   MOV AL, 38H                      ; 8-bit mode, 2 lines, 5x8 font
   CALL INST_CTRL
   MOV AL, 08H                      ; Display OFF
   CALL INST_CTRL
   MOV AL, 01H                      ; Clear display
   CALL INST_CTRL
   MOV AL, 06H                      ; Entry mode: increment cursor
   CALL INST_CTRL
   MOV AL, 0CH                      ; Display ON, cursor OFF
   CALL INST_CTRL
   RET
   
DELAY_1MS:                          ; 1ms delay subroutine
   MOV BX, 02CAH                    ; Delay counter
L1:
   DEC BX
   NOP                              ; No operation for timing
   JNZ L1
   RET
   
PRINT_STR:                          ; Print null-terminated string
   MOV AL, [SI]                     ; Load character
   CMP AL, "$"                      ; Check for string terminator
   JE EXIT_STR                      ; Exit if end of string
   CALL DATA_CTRL                   ; Display character
   INC SI                           ; Next character
   JMP PRINT_STR
EXIT_STR:
   RET
   
   ;=================================================================
   ; INTERRUPT AND TEMPERATURE HANDLING SUBROUTINES
   ;=================================================================
EN_ISR0:                            ; Enable ISR0 interrupt
   MOV DX, PIC2
   MOV AL, ICW2                     ; Interrupt vector base
   OUT DX, AL
   MOV AL, ICW4                     ; 8086 mode, normal EOI
   OUT DX, AL
   MOV AL, OCW1_ISR0                ; Enable IR0 only
   OUT DX, AL
   STI                              ; Enable interrupts
   RET
   
DEGREES:                            ; Display degree Celsius symbol
   MOV AL, 11011111B                ; Degree symbol character
   CALL DATA_CTRL
   MOV AL, 'C'                      ; 'C' for Celsius
   CALL DATA_CTRL
   RET
   
   ;=================================================================
   ; LOOKUP TABLE SUBROUTINE FOR ADC TEMPERATURE CONVERSION
   ; Input:  AL = ADC value (15H-4DH)
   ; Output: AL = Temperature (12-45) or 0 if not found
   ;=================================================================
LOOKUP_TEMP PROC
   PUSH BX                          ; Save registers
   PUSH CX
   PUSH SI
   
   LEA SI, ADC_VALUES               ; Point to ADC values table
   MOV CX, TABLE_SIZE               ; Number of entries to search
   MOV BX, 0                        ; Index counter
   
LOOKUP_LOOP:
   CMP AL, [SI+BX]                  ; Compare with current ADC value
   JE FOUND_VALUE                   ; If found, get temperature
   INC BX                           ; Next index
   LOOP LOOKUP_LOOP
   
   ; Value not found
   MOV AL, 0                        ; Return 0 for invalid ADC value
   JMP LOOKUP_EXIT
   
FOUND_VALUE:
   LEA SI, TEMP_VALUES              ; Point to temperature values table
   MOV AL, [SI+BX]                  ; Get corresponding temperature
   
LOOKUP_EXIT:
   POP SI                           ; Restore registers
   POP CX
   POP BX
   RET
   
LOOKUP_TEMP ENDP
   
DISP_FSPEED:                        ; Display fan speed on LCD
   PUSH AX
   PUSH BX
   
   MOV AL, 09FH                     ; Set cursor to third line, position 15
   CALL INST_CTRL
   
   MOV AL, FSPEED                   ; Check fan speed setting
   CMP AL, 0
   JE DISP_LOW                      ; Display "LOW"
   CMP AL, 1
   JE DISP_MED                      ; Display "MED"
   CMP AL, 2
   JE DISP_HIGH                     ; Display "HIGH"
   
DISP_LOW:                           ; Display LOW speed
   LEA SI, LOW_MSG
   CALL PRINT_STR
   MOV AL, 01H                      ; Set PWM for low speed
   CALL ADJ_SPEED
   JMP EXIT_DISP_FSPEED
   
DISP_MED:                           ; Display MEDIUM speed
   LEA SI, MED_MSG
   CALL PRINT_STR
   MOV AL, 02H                      ; Set PWM for medium speed
   CALL ADJ_SPEED
   JMP EXIT_DISP_FSPEED
   
DISP_HIGH:                          ; Display HIGH speed
   LEA SI, HIGH_MSG
   CALL PRINT_STR
   MOV AL, 03H                      ; Set PWM for high speed
   CALL ADJ_SPEED
   
EXIT_DISP_FSPEED:
   POP AX
   POP BX
   RET
   
DISPLAY_ROOMT:                      ; Display room temperature on LCD
   PUSH AX
   PUSH BX
   
   MOV AL, 0CBH                     ; Set cursor to first line, position 11
   CALL INST_CTRL
   
   ; Check if ADC error flag is set
   CMP ADC_ERROR_FLAG, 1
   JE DISPLAY_ERROR_MSG
   
   ; No error - display normal temperature
   XOR AX, AX                       ; Clear AX
   XOR BX, BX                       ; Clear BX
   
   MOV AL, ROOM_T                   ; Convert temperature to ASCII
   XOR AH, AH
   MOV BL, 10                       ; Divide by 10
   DIV BL                           ; AL = tens digit, AH = ones digit
   
   ADD AL, 30H                      ; Convert to ASCII
   ADD AH, 30H
   CALL DATA_CTRL                   ; Display tens digit
   
   MOV AL, AH                       ; Display ones digit
   CALL DATA_CTRL
   
   LEA SI, CELSIUS_MSG              ; Display ".0°C"
   CALL PRINT_STR
   CALL DEGREES                     ; Display degree symbol
   JMP EXIT_DISPLAY_ROOMT
   
DISPLAY_ERROR_MSG:                  ; Display error message
   LEA SI, ERROR_MSG                ; Display "ERR"
   CALL PRINT_STR
   
   ; Clear the remaining characters in the temperature field
   MOV CX, 4                        ; Counter for 4 characters to clear
CLEAR_TEMP_FIELD:
   MOV AL, ' '                      ; Space character to clear
   CALL DATA_CTRL
   LOOP CLEAR_TEMP_FIELD                 ; Display degree symbol
   
EXIT_DISPLAY_ROOMT:
   POP BX
   POP AX
   RET
   
DISP_DTEMP:                         ; Display desired temperature on LCD
   PUSH AX
   PUSH BX
   
   MOV AL, 08BH                     ; Set cursor to second line, position 11
   CALL INST_CTRL
   
   XOR AX, AX                       ; Clear AX
   XOR BX, BX                       ; Clear BX
   
   MOV AL, DTEMP                    ; Convert temperature to ASCII
   XOR AH, AH
   MOV BL, 10                       ; Divide by 10
   DIV BL                           ; AL = tens digit, AH = ones digit
   
   ADD AL, 30H                      ; Convert to ASCII
   ADD AH, 30H
   CALL DATA_CTRL                   ; Display tens digit
   
   MOV AL, AH                       ; Display ones digit
   CALL DATA_CTRL
   
   LEA SI, CELSIUS_MSG              ; Display ".0°C"
   CALL PRINT_STR
   CALL DEGREES                     ; Display degree symbol
   
   POP BX
   POP AX
   RET
   
ADJ_SPEED:                          ; Adjust fan motor speed via PWM
   MOV DX, PORTH                    ; Fan speed control port
   OUT DX, AL                       ; Set speed (01H=Low, 02H=Med, 03H=High)
   RET
   
CODE ENDS
END START